#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/train?createDatabaseIfNotExist=true
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#  application:
#    name: Logbacking-service
#
#
#
#server:
#  port: 9999